-- MySQL Script generated by MySQL Workbench
-- Thu Feb  5 16:20:14 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `AuditLog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AuditLog` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `AuditLog` (
  `UUID` BINARY(16) NOT NULL,
  `Usuario_UUID` BINARY(16) NOT NULL,
  `Accion` ENUM("CREAR", "ACTUALIZAR", "ELIMINAR") NOT NULL,
  `TablaAfectada` VARCHAR(50) NULL,
  `RegistroUUID` BINARY(16) NULL,
  `DatosAnteriores` JSON NULL,
  `DatosNuevos` JSON NULL,
  `Fecha` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`UUID`, `Usuario_UUID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `AyudasTecnicas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AyudasTecnicas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `AyudasTecnicas` (
  `UUID` BINARY(16) NOT NULL,
  `Usuario_UUID` BINARY(16) NOT NULL,
  `Observacion` VARCHAR(500) NULL,
  `Fecha` DATE NOT NULL,
  `TipoAdyuda_UUID` BINARY(64) NOT NULL,
  `Paciente_UUID` BINARY(16) NOT NULL,
  PRIMARY KEY (`UUID`, `Usuario_UUID`, `TipoAdyuda_UUID`, `Paciente_UUID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Consulta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Consulta` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Consulta` (
  `UUID` BINARY(16) NOT NULL,
  `Fecha` DATE NOT NULL,
  `Usuario_UUID` BINARY(16) NOT NULL,
  `Observacion` VARCHAR(500) NULL,
  `Paciente_UUID` BINARY(16) NOT NULL,
  `Doctor_UUID` BINARY(16) NOT NULL,
  PRIMARY KEY (`UUID`, `Usuario_UUID`, `Paciente_UUID`, `Doctor_UUID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Consulta_has_Patologia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Consulta_has_Patologia` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Consulta_has_Patologia` (
  `Consulta_UUID` BINARY(16) NOT NULL,
  `Patologia_UUID` BINARY(16) NOT NULL,
  PRIMARY KEY (`Consulta_UUID`, `Patologia_UUID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Doctor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Doctor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Doctor` (
  `UUID` BINARY(16) NOT NULL,
  `Personas_UUID` BINARY(16) NOT NULL,
  PRIMARY KEY (`UUID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Doctor_has_Especialidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Doctor_has_Especialidades` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Doctor_has_Especialidades` (
  `Doctor_UUID` BINARY(16) NOT NULL,
  `Especialidades_UUID` BINARY(16) NOT NULL,
  PRIMARY KEY (`Doctor_UUID`, `Especialidades_UUID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Especialidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Especialidades` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Especialidades` (
  `UUID` BINARY(16) NOT NULL,
  `Espacialidad` VARCHAR(100) NULL,
  PRIMARY KEY (`UUID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `IMG`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IMG` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `IMG` (
  `UUID` BINARY(16) NOT NULL,
  `Ruta` VARCHAR(100) NOT NULL,
  `Consulta_UUID` BINARY(16) NOT NULL,
  PRIMARY KEY (`UUID`, `Consulta_UUID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `NucleoFamiliar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NucleoFamiliar` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `NucleoFamiliar` (
  `Paciente_UUID` BINARY(16) NOT NULL,
  `Personas_UUID` BINARY(16) NOT NULL,
  `Parentesco` ENUM('MADRE', 'PADRE', 'ESPOSO', 'ESPOSA', 'CONCUBINO', 'CONCUBINA', 'HIJO', 'HIJA', 'HERMANO', 'HERMANA', 'ABUELO', 'ABUELA', 'NIETO', 'NIETA', 'TIO', 'TIA', 'SOBRINO', 'SOBRINA', 'PRIMO', 'PRIMA', 'SUEGRO', 'SUEGRA', 'YERNO', 'NUERA', 'CUÑADO', 'CUÑADA', 'TUTOR_LEGAL', 'OTRO') NOT NULL,
  PRIMARY KEY (`Paciente_UUID`, `Personas_UUID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Paciente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Paciente` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Paciente` (
  `UUID` BINARY(16) NOT NULL,
  `Personas_UUID` BINARY(16) NOT NULL,
  `EstadoCivil` ENUM("SOLTERO", "CASADO", "DIVORCIADO", "VIUDO") NULL,
  `LugarNacimiento` VARCHAR(100) NULL,
  `PaisNacimiento` VARCHAR(100) NULL,
  `Ocupacion` VARCHAR(100) NULL,
  `GradoInstruccion` ENUM('Sin instrucción', 'Primaria Incompleta', 'Primaria Completa', 'Secundaria Incompleta', 'Secundaria Completa', 'Técnico Medio', 'TSU', 'Universitario Incompleto', 'Universitario Completo', 'Postgrado', 'Doctorado') NULL,
  `Profesion` VARCHAR(100) NULL,
  `Salario Mensual` VARCHAR(45) NULL,
  `CarnetPatria` TINYINT NULL DEFAULT 0,
  `TipoDeSolicitud` VARCHAR(1000) NULL,
  `Alergico` VARCHAR(1000) NULL DEFAULT 0,
  `TipoVivienda` VARCHAR(100) NULL,
  `DescripcionVIvienda` VARCHAR(100) NULL,
  `TenenciaVivienda` VARCHAR(100) NULL,
  `Observaciones` VARCHAR(1000) NULL,
  `Usuario_UUID` BINARY(16) NOT NULL,
  PRIMARY KEY (`UUID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Patologia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Patologia` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Patologia` (
  `UUID` BINARY(16) NOT NULL,
  `Name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`UUID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Personas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Personas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Personas` (
  `UUID` BINARY(16) NOT NULL,
  `FullName` VARCHAR(150) NOT NULL,
  `Cedula` VARCHAR(45) NOT NULL,
  `Tipo_Cedula` ENUM("E", "V", "G", "J", "P") NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  `Tipo` VARCHAR(45) NULL,
  `Nacimiento` DATE NOT NULL,
  `Direccion` VARCHAR(45) NULL,
  PRIMARY KEY (`UUID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `TipoAdyuda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TipoAdyuda` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `TipoAdyuda` (
  `UUID` BINARY(16) NOT NULL,
  `Name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`UUID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Usuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Usuario` (
  `UUID` BINARY(16) NOT NULL,
  `UserName` VARCHAR(100) NOT NULL,
  `Pashash` BINARY(64) NOT NULL,
  `Nivel` INT NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Personas_UUID` BINARY(16) NOT NULL,
  `Status` VARCHAR(45) NULL,
  PRIMARY KEY (`UUID`, `Personas_UUID`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
